name: E.P.-phone-Home

on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest
      
          
     
    
    
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      VER_NUMBER: $GITHUB_RUN_NUMBER
      
      
    steps:
    - name: Checking main branch from GitHub
      uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    
    - name: Set version number
      run: echo ::set-env name=VER_NUMBER_WITH_OFFSET::$((${{ env.VER_NUMBER }} - 143))
   
    - name: Step 5 - (a-b-c) - Compile and Package with Maven and Increase Jar version
      run: |
           cd my-app 
           mvn -U versions:set -DnewVersion=1.0.$VER_NUMBER_WITH_OFFSET
           mvn -B package -f pom.xml 
     
    - uses: actions/cache@v1
      with:
           path: ~/.m2/repository
           key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
           restore-keys: |
             ${{ runner.os }}-maven-
   
    - name: List files in my-app directory
      run: ls -a my-app/target/
      
    - name: Copy artifact to folder staging 
      run:  |
            mkdir staging
            cp my-app/target/m*.jar staging
           
    - name: Step 5 - d) Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: Kepler-Artifact
        path: staging
        
    - name: Run Hello World
      run: |
           cd my-app 
           java -cp target/my-app-1.0.$VER_NUMBER_WITH_OFFSET.jar com.mycompany.app.App    
     
    - name: Step 5 - e) Create a Docker image 
      run : |
            docker build -t epy1234/ep-phone-home:1.0.$VER_NUMBER_WITH_OFFSET . 
            docker images
      
    - name: Step 5 - f) Push image to DockerHub and remove image locally
      run : |
            docker push epy1234/ep-phone-home:1.0.$VER_NUMBER_WITH_OFFSET
            docker rmi epy1234/ep-phone-home:1.0.$VER_NUMBER_WITH_OFFSET
            
      
    - name: Step 5 - g) Pull and Run docker from DockerHub
      run : |
            docker run epy1234/ep-phone-home:1.0.$VER_NUMBER_WITH_OFFSET
            docker ps -a  
            
    - name: Finally
      run : echo "Pick Me Home!!!"
    
            
           
    
        
    
    
    
        
      
